# Generated by Django 5.0.7 on 2024-08-07 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0002_staff_customer_order_orderitem_shippingaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('people', models.CharField(choices=[('1', '1 person'), ('2', '2 people'), ('3', '3 people'), ('4', '4 people'), ('family', 'Family')], max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
