# Generated by Django 5.0.7 on 2024-08-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('1', 'approved'), ('1', 'declined'), ('1', 'pending')], default=None, max_length=50),
        ),
    ]
