# Generated by Django 5.0.7 on 2024-08-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0004_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Order',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'declined'), ('3', 'approved')], default='3', max_length=50),
        ),
    ]
