# Generated by Django 5.0.7 on 2024-08-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0005_rename_order_shippingaddress_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
